[versions]
# Library and plugin versions
kotlin = "2.2.20"

# kotlin-playground module's configuration information
kotlinPlayground-group = "com.kotlin.playground"
kotlinPlayground-version = "1.0.0"
kotlinPlayground-mainClass = "com.kotlin.playground.PlaygroundKt"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }

[plugins]
application = { id = "application" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }