[versions]
# Library and plugin versions
kotlin = "2.2.20"
composeMultiplatform = "1.10.0-beta01"
jetbrainsAnnotations = "26.0.2"

# kotlin-playground module's configuration information
kotlinPlayground-group = "com.kotlin.playground"
kotlinPlayground-version = "1.0.0"
kotlinPlayground-mainClass = "com.kotlin.playground.PlaygroundKt"

# compose-playground module's configuration information
composePlayground-group = "com.compose.playground"
composePlayground-version = "1.0.0"
composePlayground-mainClass = "com.compose.playground.PlaygroundKt"

# trying-kotlin module's configuration information
tryingKotlin-group = "com.trying.kotlin"
tryingKotlin-version = "1.0.0"

# practice-solutions module's configuration information
practiceSolutions-group = "com.practice.solutions"
practiceSolutions-version = "1.0.0"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrainsAnnotations" }

[plugins]
application = { id = "application" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }